//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Id { get; set; }
        public int SellerId { get; set; }
        public int Price { get; set; }
        public string Address { get; set; }
        public int Quantity { get; set; }
    
        public virtual Farmer Farmer { get; set; }
    }
}
