//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string ServiceType { get; set; }
        public int ProviderId { get; set; }
        public System.DateTime Date { get; set; }
        public int Time { get; set; }
        public int Rate { get; set; }
        public string Bill { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual User User { get; set; }
    }
}
